/**
 * test_elf.c — ELF Loader Tests (Phase 16)
 *
 * Tests:
 *  1. Validation rejects   — bad magic, wrong class, truncated buffer
 *  2. Load from memory     — embed hello.elf, load via elf_exec_mem(),
 *                             verify task spawned and ran
 *  3. Load from filesystem — write embedded ELF to SimpleFS, exec via
 *                             elf_exec(), verify output
 *  4. Resource cleanup     — PMM free count recovers after task completes
 *
 * The embedded hello.elf is generated by the build system into
 * user/hello_elf.h via xxd.
 */

#include "test_elf.h"
#include "../drivers/screen.h"
#include "../kernel/exec/elf.h"
#include "../kernel/task/task.h"
#include "../kernel/task/sched.h"
#include "../kernel/sys/timer.h"
#include "../kernel/mem/pmm.h"
#include "../kernel/mem/paging.h"
#include "../fs/simplefs.h"
#include "../libc/string.h"
#include "../libc/stdio.h"

/* ── Embedded hello.elf binary (generated by Makefile: xxd -i) ──────────── */
#include "../user/hello_elf.h"

/* ─── Helpers ───────────────────────────────────────────────────────────── */

static int pass_count = 0;
static int fail_count = 0;

#define TEST_ASSERT(cond, msg) do {                             \
    if (cond) {                                                 \
        kprintf("  [PASS] %s\n", msg);                         \
        pass_count++;                                           \
    } else {                                                    \
        kprintf("  [FAIL] %s\n", msg);                         \
        fail_count++;                                           \
    }                                                           \
} while (0)

/**
 * busy_wait — Spin for @ticks timer ticks (at 100 Hz, 1 tick ≈ 10 ms)
 */
static void busy_wait_ticks(uint32_t ticks) {
    uint32_t start = get_timer_ticks();
    while ((get_timer_ticks() - start) < ticks) {
        __asm__ volatile("hlt");   /* sleep until next interrupt */
    }
}

/* ─── Test 1: ELF Validation ────────────────────────────────────────────── */

static void test_elf_validate(void) {
    kprint("\n--- Test 1: ELF Validation ---\n");

    /* NULL buffer */
    TEST_ASSERT(elf_validate(0, 0) == -1,
                "NULL buffer rejected");

    /* Too small */
    uint8_t tiny[4] = { 0x7f, 'E', 'L', 'F' };
    TEST_ASSERT(elf_validate(tiny, sizeof(tiny)) == -1,
                "Truncated buffer rejected");

    /* Bad magic */
    uint8_t bad_magic[64];
    memset(bad_magic, 0, sizeof(bad_magic));
    bad_magic[0] = 0x00;  /* wrong magic */
    bad_magic[1] = 'E';
    bad_magic[2] = 'L';
    bad_magic[3] = 'F';
    TEST_ASSERT(elf_validate(bad_magic, sizeof(bad_magic)) == -1,
                "Bad magic rejected");

    /* Correct header from embedded ELF */
    TEST_ASSERT(elf_validate(user_hello_elf, user_hello_elf_len) == 0,
                "Valid hello.elf accepted");
}

/* ─── Test 2: Load from Memory ──────────────────────────────────────────── */

static void test_elf_mem_load(void) {
    kprint("\n--- Test 2: ELF Load from Memory ---\n");

    task_t *t = elf_exec_mem(user_hello_elf, user_hello_elf_len, "elf_mem");
    TEST_ASSERT(t != 0, "elf_exec_mem() returned non-NULL task");

    if (t) {
        TEST_ASSERT(t->is_user == 1,   "Task is Ring 3");
        TEST_ASSERT(t->cr3 != 0,       "Task has private CR3");
        TEST_ASSERT(t->page_dir != 0,  "Task has page directory");

        /* Let the task run and finish */
        busy_wait_ticks(30);

        /* Reap dead tasks */
        task_reap();
    }
}

/* ─── Test 3: Load from Filesystem ──────────────────────────────────────── */

static void test_elf_fs_load(void) {
    kprint("\n--- Test 3: ELF Load from Filesystem ---\n");

    /* Write the embedded ELF to SimpleFS */
    fs_create("hello.elf", 1 /* FS_TYPE_FILE */);
    int rc = fs_write_file("hello.elf", user_hello_elf, user_hello_elf_len);
    TEST_ASSERT(rc == 0, "Wrote hello.elf to SimpleFS");

    /* Execute it */
    task_t *t = elf_exec("hello.elf", "elf_fs");
    TEST_ASSERT(t != 0, "elf_exec() returned non-NULL task");

    if (t) {
        TEST_ASSERT(t->is_user == 1, "Task is Ring 3");

        /* Let the task run and finish */
        busy_wait_ticks(30);
        task_reap();
    }

    /* Non-existent file */
    task_t *bad = elf_exec("nofile.elf", "bad");
    TEST_ASSERT(bad == 0, "elf_exec() returns NULL for missing file");

    /* Clean up test file */
    fs_delete("hello.elf");
}

/* ─── Test 4: Resource Cleanup ──────────────────────────────────────────── */

static void test_elf_cleanup(void) {
    kprint("\n--- Test 4: Resource Cleanup ---\n");

    uint32_t free_before = get_free_memory();

    /* Spawn, let run, reap */
    task_t *t = elf_exec_mem(user_hello_elf, user_hello_elf_len, "elf_clean");
    TEST_ASSERT(t != 0, "Spawned cleanup test task");

    if (t) {
        busy_wait_ticks(30);
        task_reap();
    }

    uint32_t free_after = get_free_memory();

    /* All pages should be reclaimed (within 1 page tolerance for
     * possible scheduler / timer allocation races) */
    int diff = (int)free_before - (int)free_after;
    if (diff < 0) diff = -diff;
    TEST_ASSERT(diff <= 4096, "PMM pages reclaimed after task exit");
}

/* ─── Public entry point ────────────────────────────────────────────────── */

void test_elf(void) {
    kprint("\n=============================\n");
    kprint("    ELF LOADER TESTS (Phase 16)\n");
    kprint("=============================\n");

    pass_count = 0;
    fail_count = 0;

    test_elf_validate();
    test_elf_mem_load();
    test_elf_fs_load();
    test_elf_cleanup();

    kprintf("\nELF Tests: %d passed, %d failed\n", pass_count, fail_count);
    kprint("=============================\n");
}
